[project]
name = "HoeWarmIsHetInDelft"
version = "0.1.0"
requires_python = ">=3.12"
dependencies = [
  "httpx",
  "beautifulsoup4",
]
[project.optional-dependencies]
dev = [
  "pytest",
  "coverage",
  "black",
]