[project]
name = "HoeWarmIsHetInDelft"
version = "0.1.0"
requires-python = ">=3.12"
description = "Coding tasks example package for retrieving weather"
readme = "README.md"
license = { file = "LICENSE.md" }
dependencies = [
  "httpx",
  "beautifulsoup4",
]
